language: python

python:
  - "2.7"
  - "3.3"

branches:
  only:
    - master

before_install:
  - pip install pip --upgrade
  - pip install -r requirements.txt
  - pip install -r test_web/requirements.txt

install:
  - python setup.py install

script:
  - python manager.py test
