language: python

python:
  - "2.7"

branches:
  only:
    - master

matrix:
  include:
    - python: "2.7"
      env: TEST_SUITE=suite_2_7
    - python: "3.3"
      env: TEST_SUITE=suite_3_3
    - python: "pypy"
      env: TEST_SUITE=suite_pypy

before_install:
  - pip install pip --upgrade
  - pip install -r requirements.txt
  - pip install -r test_web/requirements.txt

install:
  - python setup.py install

script: ./scripts/run-tests.sh
