language: python

python:
  - "2.7"

branches:
  only:
    - master

before_install:
  - pip install pip --upgrade

install:
  - python setup.py install

before_script:
  - pip install -r requirements.txt
  - pip install -r test_web/requirements.txt

script:
  - python manage.py test
  - coverage run --source='.' manage.py test
  - coverage report -m --skip-covered
